Add pronouns in profile
ncosd/food-pantry-app pull request #272
Opened 2024-01-09 19:07 UTC by rakshitriya

### Related Issue
Adds pronouns during sign up and profile page as an optional field.
Closes #238

### Testing
<img width="537" alt="image" src="https://github.com/ncosd/food-pantry-app/assets/140355188/777032b4-3081-4988-bbb7-911bb4909b15">

### Stakeholders
@dherbst , could you please check this?

2024-01-09 19:20 UTC, dherbst requested changes
Consider changing the word "pronoun" to "pronouns" because there is more than one expected.

I also added a placeholder as a hint to the user, similar to what slack does: (she/her, they/them, he/him, etc)

2024-01-09 19:20 UTC, dherbst commented on web/admin/src/components/VolunteerRegistrationForm.vue
> +                <label class="form-label">Pronoun</label>
```suggestion
                <label class="form-label">Pronouns</label>
```

2024-01-09 19:20 UTC, dherbst commented on web/admin/src/views/ProfilePage.vue
> +        <label class="form-label" for="pronoun">Pronoun</label>
```suggestion
        <label class="form-label" for="pronoun">Pronouns</label>
```

2024-01-09 19:20 UTC, dherbst commented on web/admin/src/views/ProfilePage.vue
> +        <input class="form-control" v-model="profile.pronoun" autocomplete="pronoun">
```suggestion
        <input class="form-control" v-model="profile.pronoun" autocomplete="pronouns" placeholder="(she/her, they/them, he/him, etc)">
```

2024-01-10 13:23 UTC, rakshitriya commented
Committed your changes!

2024-01-10 13:50 UTC, dherbst commented on web/admin/src/components/VolunteerRegistrationForm.vue
> +                <input class="form-control" v-model="profile.pronoun" autocomplete="phone">
```suggestion
                <input class="form-control" v-model="profile.pronoun" placeholder="(she/her, they/them, he/him, etc)">
```
There isn't an autocomplete for pronouns. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2024-01-10 13:50 UTC, dherbst commented on web/admin/src/views/ProfilePage.vue
> +        <input class="form-control" v-model="profile.pronoun" autocomplete="pronouns" placeholder="(she/her, they/them, he/him, etc)">
```suggestion
        <input class="form-control" v-model="profile.pronoun" placeholder="(she/her, they/them, he/him, etc)">
```

2024-01-10 13:59 UTC, dherbst approved these changes
lgtm

2024-01-10 13:59 UTC, dherbst commented
Thanks for doing this one!

2024-01-10 13:59 UTC, merged

2024-01-10 14:01 UTC, rakshitriya commented
Thankyou for giving me a chance! 🎉